# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Feature
  description: Feature section
  icon: "stars"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: /images/feature/feature-card-one.png
  image_alt: Message inbox
  title: Text Message in One Minute
  description: The stats are in our favour. SaaSFlow doesn't just help you with your email marketing, we get you customer relationships that last.
  button:
    link: /signup
    text: Try This Free
  reversed: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
