# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: FAQ
  description: FAQ section
  icon: "checklist"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: Have
  title_suffix: Questions?
  description: The stats are in our favour. SaaSFlow doesn't just help you with your email marketing, we get you customer relationships that last.
  faq:
    - title: What if I unplug all selected apps at once?
      description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim illo quasi quia doloremque dignissimos rerum perspiciatis, officiis optio natus beatae!

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
