# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Pricing Table
  description: Pricing table section
  icon: "table_rows"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  pricing_tier:
    - tier: free
      highlight_tier: false
      description: For starters Includes unlimited members
      price: 0
      has_discount: false
      discount_price: 0
      feature:
        - item: 1 Site Activation
          active_feature: true
        - item: 1 Year Premium Support
          active_feature: true
        - item: Regular Update for 1 Year
          active_feature: true
        - item: 90+ Widgets & Extensions
          active_feature: true
        - item: 23+ Templates
          active_feature: true
        - item: Over 800 Section Blocks
          active_feature: false
        - item: Support
          active_feature: false
        - item: 3 filters
          active_feature: false
        - item: Unlimited activity history
          active_feature: false
      button:
        link: /login
        text: Try This Free

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
