# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Privacy
  description: Privacy section
  icon: "lock"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  terms_and_conditions:
    - heading: Sendit Terms And Conditions
      description: "A slider is great way to display a slideshow The WordPress sites being easy to use, offers many plugins for slider. You could imagine slideshows in your head and make them true on the screen."
    - heading: Account Information & Payments
      description: "The main benefit of using sliders is presenting all the contents in a visually pleasing manner. The WordPress sites being easy to use, offers many plugins for slider. You could imagine slideshows in your head and make them true on the screen."

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
