# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Pricing Hero
  description: Pricing Hero section
  icon: "credit_card"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Choose a plan that works best for you.
  description: The stats are in our favour. SaaSFlow doesn't just help you with your email marketing, we get you customer relationships that last.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
