# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Hero
  description: About Hero section
  icon: "apps"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: One mission to make the better marketing
  description: The stats are in our favour. SaaSFlow doesn't just help you with your email marketing.
  hero_images:
    - image_path: /images/about/aboutfeature-two.png
      placer: front_buttom
    - image_path: /images/about/aboutfeature-three.png
      placer: back_top_right
    - image_path: /images/about/aboutfeature-four.png
      placer: back_top_left
  btn:
    text: "See more"
    link: "#counter-up"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
  placer:
    type: select
    options:
      values:
        - front_buttom
        - back_top_right
        - back_top_left
